Sitemap Creator version 1.0.1 (#1)
## 修复
- fix(js): 更正获取生成脚本来源 by @DuckDuckStudio & @fjwxzde 
- fix(action): 更正拼写 by @DuckDuckStudio 

## 新功能
- feat(action): 可以通过设置 `labels: xxx` 来为创建的拉取请求添加标签 by @DuckDuckStudio 
- feat(action): 可以通过设置 `auto_merge: s` 等来启用自动合并并指定自动合并方式 by @DuckDuckStudio 

## 优化
- pref(js): 添加更多的 DEBUG 输出 by @DuckDuckStudio 

**Full Changelog**: https://github.com/DuckDuckStudio/Sitemap_Creator/compare/1.0.0...1.0.1-Pre-Release

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -50,6 +50,14 @@ inputs:
     description: 控制调试输出的开关
     default: false
 
+  labels:
+    required: false
+    description: 创建拉取请求时添加的标签
+
+  auto_merge:
+    required: false
+    description: 设置启用自动合并的类型 (不指定则不启用自动合并，可以使用 merge、rebase、squash)
+
 runs:
   using: composite
   steps:
@@ -78,39 +86,114 @@ runs:
         DEBUG: ${{ inputs.debug }}
       run: |
         # 获取生成脚本
-        git clone https://github.com/fjwxzde/Sitemap_Creator
+        git clone https://github.com/DuckDuckStudio/Sitemap_Creator -b main # 稳定版
         cp Sitemap_Creator/generate-sitemap.mjs Sitemap_Creator.mjs
         rm -r Sitemap_Creator
 
         # 生成网站地图
         node Sitemap_Creator.mjs
+        rm Sitemap_Creator.mjs
 
     - name: 提交并推送 sitemap.xml
       shell: bash
       env:
         GH_TOKEN: ${{ inputs.token }}
+        LABELS: ${{ inputs.labels }}
+        DEBUG: ${{ inputs.debug }}
+        AUTO_MERGE: ${{ inputs.auto_merge }}
       run: |
+        # 参数处理
         # 获取当前日期和时间
         DATE_TIME=$(date '+%Y/%m/%d %H:%M')
 
+        # 移除标签参数中的特殊字符
+        CLEAN_LABELS=$(echo "$LABELS" | sed "s/[\"\'\`]*//g") # 移除 " ' ` 字符
+        if [[ ("$LABELS" != "$CLEAN_LABELS") && ("$DEBUG") ]]; then
+          echo "[DEBUG] 标签包含特殊字符，已移除: $LABELS -> $CLEAN_LABELS"
+        fi
+
+        # 如果 AUTO_MERGE 为空字符串，则不做任何操作
+        if [[ -z "$AUTO_MERGE" ]]; then
+          if [[ "$DEBUG" ]]; then
+            echo "[DEBUG] 不启用自动合并，因为自动合并方式为空"
+          fi
+          CLEAN_AUTO_MERGE=""
+        else
+          # 格式化自动合并方式
+          CLEAN_AUTO_MERGE=$(echo "$AUTO_MERGE" | tr '[:upper:]' '[:lower:]' | sed "s/[\"\'\`-]//g") # 转为小写并移除 " ' ` -
+
+          # 根据输入值设置对应的自动合并方式
+          case "$CLEAN_AUTO_MERGE" in
+            "s"|"squash"|"压缩"|"压缩合并"|"压缩自动合并")
+              CLEAN_AUTO_MERGE="squash"
+              ;;
+            "m"|"merge"|"合并"|"合并提交"|"提交")
+              CLEAN_AUTO_MERGE="merge"
+              ;;
+            "r"|"rebase"|"变基"|"变基合并"|"变基自动合并")
+              CLEAN_AUTO_MERGE="rebase"
+              ;;
+            *)
+              echo "[ERROR] 未知的自动合并方式: $AUTO_MERGE"
+              echo "[TIP] 可用的自动合并方式: 压缩、合并、变基"
+              exit 1
+              ;;
+          esac
+        fi
+
+        # 如果自动合并方式进行了格式化，输出调试信息
+        if [[ ("$AUTO_MERGE" != "$CLEAN_AUTO_MERGE") && ("$DEBUG") ]]; then
+          echo "[DEBUG] 已格式化自动合并方式: $AUTO_MERGE -> $CLEAN_AUTO_MERGE"
+        fi
+
+        # ================
+
+        # 生成分支名
         BRANCH_NAME="sitemap-update-$(date +%Y%m%d%H%M%S)"
         git checkout -b $BRANCH_NAME
-        echo "已创建分支 $BRANCH_NAME"
+        echo "[INFO] 已创建新分支: $BRANCH_NAME"
 
+        # 配置 Git 用户
         git config user.name "github-actions[bot]"
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
+        # 提交并推送 sitemap.xml
         git add docs/sitemap.xml
-        git commit -m "[${DATE_TIME}] Auto update sitemap"
+        git commit -m "[${DATE_TIME}] 自动更新网站地图"
         git push --set-upstream origin $BRANCH_NAME
 
         # 生成工作流 URL
         WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
 
-        # 使用 GitHub CLI 创建 PR，动态设置 body 内容为工作流链接
-        gh pr create --title "[${DATE_TIME}] Auto update sitemap" \
-                      --body "Created through the [workflow](${WORKFLOW_URL}).<br>Using [Sitemap Creator Action by DuckDuckStudio](https://github.com/DuckDuckStudio/Sitemap_Creator)" \
-                      --base ${{ inputs.base_branch }} \
-                      --head $BRANCH_NAME
+        # 创建拉取请求
+        PR_URL=$(gh pr create --title "[${DATE_TIME}] 自动更新网站地图" \
+                              --body "此拉取请求通过 [工作流](${WORKFLOW_URL}) 使用 [Sitemap Creator](https://github.com/DuckDuckStudio/Sitemap_Creator) 创建。" \
+                              --base ${{ inputs.base_branch }} \
+                              --head $BRANCH_NAME)
 
-        echo "Pull Request 创建完成。"
+        echo "[INFO] 已创建拉取请求: $PR_URL"
+
+        # 判断是否有清理后的标签并添加到 PR
+        if [[ -n "$CLEAN_LABELS" ]]; then
+          # 将标签按逗号分隔成数组
+          LABEL_ARRAY=($(echo "$CLEAN_LABELS" | tr ',' '\n'))
+          for LABEL in "${LABEL_ARRAY[@]}"; do
+            # 为 PR 添加标签
+            gh pr edit $PR_URL --add-label "$LABEL"
+            if [[ "$DEBUG" ]]; then
+              echo "[DEBUG] 为拉取请求添加标签: $LABEL"
+            fi
+          done
+          echo "[INFO] 已为创建的拉取请求添加指定的标签"
+        elif [[ "$DEBUG" ]]; then
+          echo "[DEBUG] 没有有效标签，跳过添加标签"
+        fi
+
+        # 判断是否启用自动合并
+        # 如果 CLEAN_AUTO_MERGE 有值（即设置了自动合并方式），进行后续处理
+        if [[ -n "$CLEAN_AUTO_MERGE" ]]; then
+          gh pr merge $PR_URL --$CLEAN_AUTO_MERGE --auto
+          echo "[INFO] 已为拉取请求启用 $CLEAN_AUTO_MERGE 合并"
+        elif [[ "$DEBUG" ]]; then
+          echo "[DEBUG] 没有有效自动合并方式，跳过启用自动合并"
+        fi
