fix(action): 补全 fi

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -201,35 +201,36 @@ runs:
 
                 # 处理不同的 HTTP 状态码
                 case $status_code in
-                    200|201)
-                      # 请求成功，检查是否有该审查者
-                      if ! jq -e ".[] | select(.login == \"$reviewer\")" response.json > /dev/null; then
-                        echo "[ERROR] $reviewer 不是仓库的协作者"
-                        if [[ "$DEBUG" ]]; then
-                          echo "[DEBUG] GitHub API 请求返回 $response"
-                        fi
-                      elif [[ "$DEBUG" ]]; then
-                        echo "[DEBUG] GitHub API 请求返回 $response\n[DEBUG] 审查者 $reviewer 鉴权成功"
+                  200|201)
+                    # 请求成功，检查是否有该审查者
+                    if ! jq -e ".[] | select(.login == \"$reviewer\")" response.json > /dev/null; then
+                      echo "[ERROR] $reviewer 不是仓库的协作者"
+                      if [[ "$DEBUG" ]]; then
+                        echo "[DEBUG] GitHub API 请求返回 $response"
                       fi
-                      ;;
-                    401)
-                      echo "[ERROR] 验证审查者时出错: 鉴权失败 (401)"
-                      exit 1
-                      ;;
-                    403)
-                      echo "[ERROR] 验证审查者时出错: 没有权限或达到速率限制 (403)"
-                      exit 1
-                      ;;
-                    404)
-                      echo "[ERROR] 验证审查者时出错: 没有权限或仓库不存在 (404)"
-                      exit 1
-                      ;;
-                    *)
-                      echo "[ERROR] 验证审查者时出错: 未命中的非成功状态码 ($status_code)"
-                      exit 1
-                      ;;
+                    elif [[ "$DEBUG" ]]; then
+                      echo "[DEBUG] GitHub API 请求返回 $response\n[DEBUG] 审查者 $reviewer 鉴权成功"
+                    fi
+                    ;;
+                  401)
+                    echo "[ERROR] 验证审查者时出错: 鉴权失败 (401)"
+                    exit 1
+                    ;;
+                  403)
+                    echo "[ERROR] 验证审查者时出错: 没有权限或达到速率限制 (403)"
+                    exit 1
+                    ;;
+                  404)
+                    echo "[ERROR] 验证审查者时出错: 没有权限或仓库不存在 (404)"
+                    exit 1
+                    ;;
+                  *)
+                    echo "[ERROR] 验证审查者时出错: 未命中的非成功状态码 ($status_code)"
+                    exit 1
+                    ;;
                 esac
               done
+            fi
 
             # 签出分支
             BRANCH_NAME="sitemap-update-$(date +%Y%m%d%H%M%S)"
